### ISSUE TITLE
[error] SSL: :certify: ssl_handshake.erl:415:Fatal error: certificate unknown

### ISSUE THREAD

**Issue by maca** [benoitc/hackney#278] opened 2016-02-07 06:41 UTC
Hi, 

I am having problems consuming an API I am developing. The problem I have is specific to my development environment, I created a CA certificate and used it to sign a host certificate, the process is greatly simplified using etcd-ca. In my linux laptop I've installed and trusted the CA certificate so curl, wget, chrome and firefox trust the certificate and I get no errors and a green bar in the case of the browsers.

Whenever I attempt to consume the api using ssl I get this error:
```
00:21:18.064 [error] SSL: :certify: ssl_handshake.erl:415:Fatal error: certificate unknown
** (MatchError) no match of right hand side value: {:error, {:tls_alert, 'certificate unknown'}}
```

Even when I pass `insecure` as option, I've also attempted passing `ssl_options`, `{verify, verify_none}`. or even passing the path to my CA.crt as `cacertfile` ssl option.

Is there anyway to let hackney/erlang/elixir use my host trusted CA certificates? just as curl, wget and Ruby do?

**Comment by benoitc** [comment] 2016-02-07 08:14
can you paste the whole options list you give to hackney? how did you create the certificate?

**Comment by maca** [comment] 2016-02-08 04:36
I am using [etcd-ca](https://github.com/coreos/etcd-ca) to ease the creation of certificates. So it goes  more or less like this:

$ etcd-ca init
$ etcd-ca new-cert myapi.local -domain '*.myapi.local'
$ etcd-ca sign myapi.local
$ etcd-ca export --insecure myapi.local > myapi.local.tar

That last command generates a tarball with the key that I can use with ngix to serve with ssl.

At this point if I use curl I get a certificate error and I have to pass the "-k" flag to make a request.

My development machine uses arch linux so to add the CA certificate and trust it I have to do this:
# cp ./.etcd-ca/ca.crt  /etc/ca-certificates/trust-source/anchors/
# trust extract-compat

From this point on curl no longer complaints about the certificate and I get a green bar on firefox.
I can't remember but I think in chrome I had to import the CA certificate.


First I tried passing `[:insecure]` that works when making a request to another site of mine where the certificate does not correspond to the actual domain, but raises the `certificate unknown` error when trying to make a request to my local api. I am using Elixir but I can try with Erlang too.

    `:hackney.request(method, uri, headers, body, [:insecure])`


Then I tried:

`
opts = [{:ssl_options, [{:cacertfile, "/home/maca/.etcd-ca/ca.crt"}]}]
:hackney.request(method, uri, headers, body, opts)
`

This time a message was logged:
 [info]  [83, 83, 76, 32, 87, 65, 82, 78, 73, 78, 71, 58, 32, 73,...]

But the error remained.

**Comment by maca** [comment] 2016-02-08 04:46
I would expect the `insecure` option to skip the certificate validation, just as the `-k` curl flag does.

**Comment by benoitc** [comment] 2016-02-08 07:41
@maca so you have the same error with the ìnsecure` setting ?

**Comment by maca** [comment] 2016-02-08 17:27
Exactly the same error, the only difference between passing `insecure` and `ssl_options`, `cacertfile` is that when passing cacertfile there is an [info] printed.

**Comment by benoitc** [comment] 2016-02-09 21:14
@maca are you sure the remote certificate chain is correct? Which version of Erlang are you using?

**Comment by maca** [comment] 2016-02-10 01:10
@benoitc 

Since I installed the CA certificate on my linux machine curl doesn't complain, and I get a green bar in firefox. I'ts only from Elixir/Erlang that I have issues. In chromium I had to manually install the CA certificate but from that point on I get a green bar and no warnings.

I am using Elixir 1.2 with Erlang 18

`Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]`

**Comment by maca** [comment] 2016-02-10 01:11
The ideal situation for me would be for hackney to ignore CA warnings with `insecure` since is in my development environment where I have issues.

**Comment by maca** [comment] 2016-02-10 01:50
I don't know if it is related to this: http://bugs.erlang.org/browse/ERL-33

This is the template that etcd-ca uses to generate the certificates:

https://github.com/coreos/etcd-ca/blob/master/Documentation/certificate_template.md

**Comment by benoitc** [comment] 2016-02-10 16:49
@maca unfortunately ignoring is not possible. Can you eventually send me a certificate so I could test?

**Comment by maca** [comment] 2016-02-10 22:24
I've sent you the certificates by email. Thanks!

**Comment by benoitc** [comment] 2016-02-25 09:52
@maca got side tracked trying to find it in my mails, thanks! I will let you know asap

**Comment by jesteracer** [comment] 2016-03-10 15:38
Had similar issues and also used insecure. And It looks like hackney memoizes this option. Is that so?

**Comment by jesteracer** [comment] 2016-03-10 20:18
@benoitc I have a module, that has 2 functions, that go to an api (one the same server) - when I added insecure to one of the calls, the other one did not get an error.

**Comment by DoomyTheFroomy** [comment] 2016-03-21 12:07
@maca @benoitc had the same problem with `erica push`, updated my erlang version to 18.2, because of [this](http://bugs.erlang.org/browse/ERL-33) bug report. And it solve my problem (after re-installing erica). Perhaps this will also solve your problem?!

**Comment by benoitc** [comment] 2016-08-26 10:35
I can't reproduce this issue. As for now you can pass any ssl options or transport you need using `{ssl_options, _}` or `{connect_options, _}` settings to the request. 

Closing this ticket. If you have more info or a working example that could help to reproduce the issue if it's still exist please create a new ticket with it.

**Closed by benoitc** 2016-08-26 10:35 UTC
