### ISSUE TITLE
{error,closed} in hackney:send_request/4 call in epubnub:subscribe/4 | Problem in HACKNEY

### ISSUE THREAD

**Issue by sagungargs** [benoitc/hackney#187] opened 2015-04-27 12:01 UTC
@benoitc Is this a bug in the improvement which is resurfacing again. ?

This is what I noticed
{1.0.6 - 2015/01/21, improvement: handle {error, closed} for HTTP 1.1 when no content-length is given).  

I also did a dbg_trace to identify the problem and here is what I got

```
10> epn_basic_examples:subscribe().
Hahahahahah....Inside Subscribe/4, BEFORE Try TimeToken <<"0">> 
(<0.129.0>) call epn_basic_examples:subscribe()
Inside Request, Clienteleleele / Conn REff: undefined 

Inside Request, PRINTING URLList: [<<"pubsub.pubnub.com">>,<<"subscribe">>,
                                   <<"demo">>,<<"hello_world">>,<<"0">>,
                                   <<"0">>] 

Inside Request, Client is undefined <<"http://pubsub.pubnub.com/subscribe/demo/hello_world/0/0">> 
(<0.129.0>) call hackney:request(get,<<"http://pubsub.pubnub.com/subscribe/demo/hello_world/0/0">>,[],<<>>,[])
(<0.129.0>) call hackney:request(get,{hackney_url,hackney_tcp_transport,http,<<"pubsub.pubnub.com">>,
             <<"/subscribe/demo/hello_world/0/0">>,
             <<"/subscribe/demo/hello_world/0/0">>,<<>>,<<>>,
             "pubsub.pubnub.com",80,<<>>,<<>>},[],<<>>,[])
(<0.129.0>) call hackney:maybe_proxy(hackney_tcp_transport,"pubsub.pubnub.com",80,[])
(<0.129.0>) call hackney:make_request(get,{hackney_url,hackney_tcp_transport,http,<<"pubsub.pubnub.com">>,
             <<"/subscribe/demo/hello_world/0/0">>,
             <<"/subscribe/demo/hello_world/0/0">>,<<>>,<<>>,
             "pubsub.pubnub.com",80,<<>>,<<>>},[],<<>>,[],false)
(<0.129.0>) call hackney:host_header({hackney_url,hackney_tcp_transport,http,<<"pubsub.pubnub.com">>,
             <<"/subscribe/demo/hello_world/0/0">>,
             <<"/subscribe/demo/hello_world/0/0">>,<<>>,<<>>,
             "pubsub.pubnub.com",80,<<>>,<<>>},[])
(<0.129.0>) call hackney:send_request(#Ref<0.0.0.931>,{get,<<"/subscribe/demo/hello_world/0/0">>,
     [{<<"Host">>,<<"pubsub.pubnub.com">>}],
     <<>>})
(<0.129.0>) call hackney:send_request({client,{1430,132707,858640},
        hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",80,
        <<"pubsub.pubnub.com">>,[],#Port<0.28545>,
        {default,#Ref<0.0.0.931>,
                 {"pubsub.pubnub.com",80,hackney_tcp_transport},
                 <0.119.0>,hackney_tcp_transport},
        #Ref<0.0.0.931>,true,hackney_pool,infinity,false,5,false,nil,nil,nil,
        connected,start,nil,normal,false,false,false,nil,waiting,nil,4096,
        <<>>,[],undefined,nil,nil,nil,nil,undefined,nil},{get,<<"/subscribe/demo/hello_world/0/0">>,
     [{<<"Host">>,<<"pubsub.pubnub.com">>}],
     <<>>})
(<0.129.0>) call hackney:maybe_redirect({ok,200,
    [{<<"Date">>,<<"Mon, 27 Apr 2015 11:05:08 GMT">>},
     {<<"Content-Type">>,<<"text/javascript; charset=\"UTF-8\"">>},
     {<<"Content-Length">>,<<"24">>},
     {<<"Cache-Control">>,<<"no-cache">>},
     {<<"Access-Control-Allow-Origin">>,<<"*">>},
     {<<"Access-Control-Allow-Methods">>,<<"GET">>},
     {<<"Connection">>,<<"keep-alive">>}],
    {client,{1430,132707,858640},
            hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",
            80,<<"pubsub.pubnub.com">>,[],#Port<0.28545>,
            {default,#Ref<0.0.0.931>,
                     {"pubsub.pubnub.com",80,hackney_tcp_transport},
                     <0.119.0>,hackney_tcp_transport},
            #Ref<0.0.0.931>,true,hackney_pool,infinity,false,5,false,nil,nil,
            {hparser,response,4096,10,0,on_body,
                     <<"[[],\"14301327058582911\"]">>,
                     {1,1},
                     undefined,[],24,undefined,<<"keep-alive">>,
                     <<"text/javascript; charset=\"utf-8\"">>,undefined,
                     waiting},
            connected,waiting,nil,normal,false,false,false,
            #Fun<hackney_request.send.2>,waiting,nil,4096,<<>>,[],
            {1,1},
            24,nil,<<"keep-alive">>,<<"GET">>,
            <<"/subscribe/demo/hello_world/0/0">>,
            <<"text/javascript; charset=\"utf-8\"">>}},{get,<<"/subscribe/demo/hello_world/0/0">>,
     [{<<"Host">>,<<"pubsub.pubnub.com">>}],
     <<>>},0)
(<0.129.0>) call hackney:reply_response({ok,200,
    [{<<"Date">>,<<"Mon, 27 Apr 2015 11:05:08 GMT">>},
     {<<"Content-Type">>,<<"text/javascript; charset=\"UTF-8\"">>},
     {<<"Content-Length">>,<<"24">>},
     {<<"Cache-Control">>,<<"no-cache">>},
     {<<"Access-Control-Allow-Origin">>,<<"*">>},
     {<<"Access-Control-Allow-Methods">>,<<"GET">>},
     {<<"Connection">>,<<"keep-alive">>}],
    {client,{1430,132707,858640},
            hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",
            80,<<"pubsub.pubnub.com">>,[],#Port<0.28545>,
            {default,#Ref<0.0.0.931>,
                     {"pubsub.pubnub.com",80,hackney_tcp_transport},
                     <0.119.0>,hackney_tcp_transport},
            #Ref<0.0.0.931>,true,hackney_pool,infinity,false,5,false,nil,nil,
            {hparser,response,4096,10,0,on_body,
                     <<"[[],\"14301327058582911\"]">>,
                     {1,1},
                     undefined,[],24,undefined,<<"keep-alive">>,
                     <<"text/javascript; charset=\"utf-8\"">>,undefined,
                     waiting},
            connected,waiting,nil,normal,false,false,false,
            #Fun<hackney_request.send.2>,waiting,nil,4096,<<>>,[],
            {1,1},
            24,nil,<<"keep-alive">>,<<"GET">>,
            <<"/subscribe/demo/hello_world/0/0">>,
            <<"text/javascript; charset=\"utf-8\"">>}},{client,{1430,132707,858640},
        hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",80,
        <<"pubsub.pubnub.com">>,[],#Port<0.28545>,
        {default,#Ref<0.0.0.931>,
                 {"pubsub.pubnub.com",80,hackney_tcp_transport},
                 <0.119.0>,hackney_tcp_transport},
        #Ref<0.0.0.931>,true,hackney_pool,infinity,false,5,false,nil,nil,nil,
        connected,start,nil,normal,false,false,false,nil,waiting,nil,4096,
        <<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.129.0>) call hackney:body(#Ref<0.0.0.931>)
(<0.129.0>) call hackney:'-body/1-fun-0-'({client,{1430,132707,858640},
        hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",80,
        <<"pubsub.pubnub.com">>,[],#Port<0.28545>,
        {default,#Ref<0.0.0.931>,
                 {"pubsub.pubnub.com",80,hackney_tcp_transport},
                 <0.119.0>,hackney_tcp_transport},
        #Ref<0.0.0.931>,true,hackney_pool,infinity,false,5,false,nil,nil,
        {hparser,response,4096,10,0,on_body,<<"[[],\"14301327058582911\"]">>,
                 {1,1},
                 undefined,[],24,undefined,<<"keep-alive">>,
                 <<"text/javascript; charset=\"utf-8\"">>,undefined,waiting},
        connected,waiting,nil,normal,false,false,false,
        #Fun<hackney_request.send.2>,waiting,nil,4096,<<>>,[],
        {1,1},
        24,nil,<<"keep-alive">>,<<"GET">>,
        <<"/subscribe/demo/hello_world/0/0">>,
        <<"text/javascript; charset=\"utf-8\"">>})
Inside Request, Body <<"[[],\"14301327058582911\"]">> 
(<0.129.0>) call hackney:reply({ok,<<"[[],\"14301327058582911\"]">>,
    {client,{1430,132707,858640},
            hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",
            80,<<"pubsub.pubnub.com">>,[],nil,nil,#Ref<0.0.0.931>,true,
            hackney_pool,infinity,false,5,false,nil,nil,nil,closed,done,nil,
            normal,false,false,false,#Fun<hackney_request.send.2>,done,nil,
            4096,<<>>,[],
            {1,1},
            24,nil,<<"keep-alive">>,<<"GET">>,
            <<"/subscribe/demo/hello_world/0/0">>,
            <<"text/javascript; charset=\"utf-8\"">>}},{client,{1430,132707,858640},
        hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",80,
        <<"pubsub.pubnub.com">>,[],#Port<0.28545>,
        {default,#Ref<0.0.0.931>,
                 {"pubsub.pubnub.com",80,hackney_tcp_transport},
                 <0.119.0>,hackney_tcp_transport},
        #Ref<0.0.0.931>,true,hackney_pool,infinity,false,5,false,nil,nil,
        {hparser,response,4096,10,0,on_body,<<"[[],\"14301327058582911\"]">>,
                 {1,1},
                 undefined,[],24,undefined,<<"keep-alive">>,
                 <<"text/javascript; charset=\"utf-8\"">>,undefined,waiting},
        connected,waiting,nil,normal,false,false,false,
        #Fun<hackney_request.send.2>,waiting,nil,4096,<<>>,[],
        {1,1},
        24,nil,<<"keep-alive">>,<<"GET">>,
        <<"/subscribe/demo/hello_world/0/0">>,
        <<"text/javascript; charset=\"utf-8\"">>})
(<0.129.0>) call hackney:maybe_update_req({client,{1430,132707,858640},
        hackney_dummy_metrics,hackney_tcp_transport,"pubsub.pubnub.com",80,
        <<"pubsub.pubnub.com">>,[],nil,nil,#Ref<0.0.0.931>,true,hackney_pool,
        infinity,false,5,false,nil,nil,nil,closed,done,nil,normal,false,false,
        false,#Fun<hackney_request.send.2>,done,nil,4096,<<>>,[],
        {1,1},
        24,nil,<<"keep-alive">>,<<"GET">>,
        <<"/subscribe/demo/hello_world/0/0">>,
        <<"text/javascript; charset=\"utf-8\"">>})
Subscribe/4, INSIDE CASE 1 : Try
Subscribe/4, INSIDE 'after' BEFORE Subscribe/4: NewTimeToken =<<"14301327058582911">> 
Hahahahahah....Inside Subscribe/4, BEFORE Try TimeToken <<"14301327058582911">> 
Inside Request, Clienteleleele / Conn REff: #Ref<0.0.0.931> 

Inside Request, PRINTING URLList: [<<"pubsub.pubnub.com">>,<<"subscribe">>,
                                   <<"demo">>,<<"hello_world">>,<<"0">>,
                                   <<"14301327058582911">>] 

PATH: <<"//subscribe/demo/hello_world/0/14301327058582911">>
HACKNEY Send REQQQUEESST return valeu: {error,closed}
(<0.129.0>) call hackney:send_request(#Ref<0.0.0.931>,{get,<<"/">>,[],<<>>})
** exception error: no match of right hand side value {error,closed}
     in function  epubnub:request/3 (/Users/N-Exchanges/Dropbox/AWS/epubnub/src/epubnub.erl, line 281)
     in call from epubnub:subscribe/4 (/Users/N-Exchanges/Dropbox/AWS/epubnub/src/epubnub.erl, line 142)
     in call from epubnub:subscribe/4 (/Users/N-Exchanges/Dropbox/AWS/epubnub/src/epubnub.erl, line 165)
11> dbg:stop().                              

```

**Comment by sagungargs** [comment] 2015-04-27 12:06
Please can you help me in identifying the above problem. We have been thoroughly testing the code and have zeroed down on Hackney after using epubnub for Erlang?OTP. Please help us in identifying the problem and a solution. I am using OTP 17.5 version so that cannot be an isse

**Comment by benoitc** [comment] 2015-04-27 16:24
I am not sure to understand the issue there. Looks like the other end decided to close the request at some point. What is the improvement you're refereeing about?

**Comment by benoitc** [comment] 2015-06-25 13:16
I tried manually with latest master to call the URLs but I wasn't able to reproduce it. Can you eventually update?

    3> hackney:get("http://pubsub.pubnub.com/subscribe/demo/hello_world/0/0").
    {ok,200,
        [{<<"Date">>,<<"Thu, 25 Jun 2015 13:07:32 GMT">>},
         {<<"Content-Type">>,
          <<"text/javascript; charset=\"UTF-8\"">>},
         {<<"Content-Length">>,<<"24">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Cache-Control">>,<<"no-cache">>},
         {<<"Access-Control-Allow-Origin">>,<<"*">>},
         {<<"Access-Control-Allow-Methods">>,<<"GET">>}],
        #Ref<0.0.1.5859>}
    4> hackney:get("http://pubsub.pubnub.com/subscribe/demo/hello_world/0/0").
    {ok,200,
        [{<<"Date">>,<<"Thu, 25 Jun 2015 13:09:47 GMT">>},
         {<<"Content-Type">>,
          <<"text/javascript; charset=\"UTF-8\"">>},
         {<<"Content-Length">>,<<"24">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Cache-Control">>,<<"no-cache">>},
         {<<"Access-Control-Allow-Origin">>,<<"*">>},
         {<<"Access-Control-Allow-Methods">>,<<"GET">>}],
        #Ref<0.0.1.5875>}
    5> {ok, _, _, Ref} =hackney:get("http://pubsub.pubnub.com/subscribe/demo/hello_world/0/0").
    {ok,200,
        [{<<"Date">>,<<"Thu, 25 Jun 2015 13:12:05 GMT">>},
         {<<"Content-Type">>,
          <<"text/javascript; charset=\"UTF-8\"">>},
         {<<"Content-Length">>,<<"24">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Cache-Control">>,<<"no-cache">>},
         {<<"Access-Control-Allow-Origin">>,<<"*">>},
         {<<"Access-Control-Allow-Methods">>,<<"GET">>}],
        #Ref<0.0.1.5888>}
    6> hackney:body(Ref).
    {ok,<<"[[],\"14352378813932403\"]">>}
    7> {ok, _, _, Ref2} =hackney:get("http://pubsub.pubnub.com/subscribe/demo/hello_world/0/14352378813932403").
    {ok,200,
        [{<<"Date">>,<<"Thu, 25 Jun 2015 13:13:32 GMT">>},
         {<<"Content-Type">>,
          <<"text/javascript; charset=\"UTF-8\"">>},
         {<<"Content-Length">>,<<"191">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Cache-Control">>,<<"no-cache">>},
         {<<"Access-Control-Allow-Origin">>,<<"*">>},
         {<<"Access-Control-Allow-Methods">>,<<"GET">>}],
        #Ref<0.0.1.5907>}
    8> hackney:body(Ref2).                                                                    {ok,<<"[[\"Hello World\",\"Hello World\",\"Hello World\",\"Hello World\",\"Hello World\",\"Hello World\",\"Hello World\",\"Hello W"...>>}
    9> {ok, _, _, Ref3} =hackney:get("http://pubsub.pubnub.com/subscribe/demo/hello_world/0/0").
    {ok,200,
        [{<<"Date">>,<<"Thu, 25 Jun 2015 13:13:59 GMT">>},
         {<<"Content-Type">>,
          <<"text/javascript; charset=\"UTF-8\"">>},
         {<<"Content-Length">>,<<"24">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Cache-Control">>,<<"no-cache">>},
         {<<"Access-Control-Allow-Origin">>,<<"*">>},
         {<<"Access-Control-Allow-Methods">>,<<"GET">>}],
        #Ref<0.0.1.5920>}
    10> hackney:body(Ref3).                                                                   {ok,<<"[[],\"14352379907817457\"]">>}
    11> {ok, _, _, Ref4} =hackney:get("http://pubsub.pubnub.com/subscribe/demo/hello_world/0/14352379907817457").
    {ok,200,
        [{<<"Date">>,<<"Thu, 25 Jun 2015 13:14:24 GMT">>},
         {<<"Content-Type">>,
          <<"text/javascript; charset=\"UTF-8\"">>},
         {<<"Content-Length">>,<<"107">>},
         {<<"Connection">>,<<"keep-alive">>},
         {<<"Cache-Control">>,<<"no-cache">>},
         {<<"Access-Control-Allow-Origin">>,<<"*">>},
         {<<"Access-Control-Allow-Methods">>,<<"GET">>}],
        #Ref<0.0.1.5933>}
    12> hackney:body(Ref4).                                                                   {ok,<<"[[\"Hello World\",\"Hello World\",\"Hello World\",\"Hello World\",\"Hello World\",\"Hello World\"],\"14352380513416507\"]">>}

**Comment by benoitc** [comment] 2015-09-15 13:01
I didn't reproduce the issue also no feedback since. Closing the issue no. Feel free to open a new one that link to it if it can be reproduced. Thanks for the ticket anyway!

**Closed by benoitc** 2015-09-15 13:01 UTC
Labels: not confirmed, working on it
