### ISSUE TITLE
Connections aren't released from the pool, causing a deadlock

### ISSUE THREAD

**Issue by jtomaszewski** [benoitc/hackney#462] opened 2017-12-13 14:57 UTC
Sometimes on production, when we run a lot of requests at the same time (hundreds per second), after a few thousands it's possible that they clutter all the connection pool.

Then, each next request always returns `connect_timeout` error. The problem never goes away; even if you wait; the connections are never released from the pool.

The only way to fix it then is one of the following ones:

- restart the server instance
- reset the pool (`hackney_pool:stop_pool(default).`)
- increase its' limit (`hackney_pool:set_max_connections(default, 1000).`), but this will still keep the zombie connections in the pool.

```elixir
pid = :hackney_pool.find_pool(:default)
iex(recruitee@10.42.157.190)7> :sys.get_state(pid)
{:state, :default, {:metrics_ng, :metrics_dummy}, 1000, 150000,
 {:dict, 50, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[[#Reference<0.0.1.234966> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.1.235139> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]],
    [[#Reference<0.0.2.228233> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.2.228281> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.3.215788> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.2.229530> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]], [],
    [[#Reference<0.0.1.235106> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]],
    [[#Reference<0.0.3.214852> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.2.229292> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]],
    [[#Reference<0.0.3.214780> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.4.218258> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]],
    [[#Reference<0.0.2.229334> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.2.229395> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]],
    [[#Reference<0.0.3.214947> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.2.229464> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]],
    [[#Reference<0.0.3.214872> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.2.229120> | {'elasticsearch-cluster', 9200, :hackney_tcp}],
     [#Reference<0.0.1.235131> |
      {'elasticsearch-cluster', 9200, :hackney_tcp}]],
(...)

 {:dict, 1, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[], [], [], [], [], [], [],
    [[{'elasticsearch-cluster', 9200, :hackney_tcp} |
      {[{{#PID<0.16759.1>, #Reference<0.0.2.253550>}, #Reference<0.0.2.253545>},
        {{#PID<0.16937.1>, #Reference<0.0.4.241506>}, #Reference<0.0.4.241504>},
        {{#PID<0.17072.1>, #Reference<0.0.3.238743>}, #Reference<0.0.3.238741>},
        {{#PID<0.17065.1>, #Reference<0.0.4.241419>}, #Reference<0.0.4.241407>},
        {{#PID<0.16911.1>, #Reference<0.0.4.241387>}, #Reference<0.0.4.241385>},
        {{#PID<0.16916.1>, #Reference<0.0.4.241235>}, #Reference<0.0.4.241233>},
        {{#PID<0.16919.1>, #Reference<0.0.4.241231>}, #Reference<0.0.4.241229>},
        {{#PID<0.16923.1>, #Reference<0.0.4.241227>}, #Reference<0.0.4.241225>},
        {{#PID<0.16922.1>, #Reference<0.0.4.241216>}, #Reference<0.0.4.241214>},
        {{#PID<0.16934.1>, #Reference<0.0.3.238603>}, #Reference<0.0.3.238601>},
        {{#PID<0.16921.1>, #Reference<0.0.2.253018>}, #Reference<0.0.2.253016>},
        {{#PID<0.16927.1>, #Reference<0.0.2.253014>}, #Reference<0.0.2.253012>},
        {{#PID<0.17085.1>, #Reference<0.0.2.253010>}, #Reference<0.0.2.253005>},
        {{#PID<0.17060.1>, #Reference<0.0.2.252998>}, #Reference<0.0.2.252996>},
        {{#PID<0.16926.1>, #Reference<0.0.2.252934>}, #Reference<0.0.2.252932>},
        {{#PID<0.17062.1>, #Reference<0.0.4.241203>}, #Reference<0.0.4.241201>},
        {{#PID<0.17061.1>, #Reference<0.0.4.241199>}, #Reference<0.0.4.241197>},
        {{#PID<0.16913.1>, #Reference<0.0.1.256874>}, #Reference<0.0.1.256872>},
        {{#PID<0.17064.1>, #Reference<0.0.4.241195>}, #Reference<0.0.4.241193>},
        {{#PID<0.17077.1>, #Reference<0.0.4.241156>}, #Reference<0.0.4.241154>},
        {{#PID<0.17081.1>, #Reference<0.0.4.241152>}, #Reference<0.0.4.241150>},
        {{#PID<0.16908.1>, #Reference<0.0.4.241149>}, #Reference<0.0.4.241147>},
        {{#PID<0.16940.1>, ...}, #Reference<0.0.4.241143>}, {{...}, ...}, {...},
(...)
        ...]}]], [], [], [], [], [], [], [], []}}},
 {:dict, 0, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}},
 {:dict, 0, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}}, 727}
```

So far:

- we can easily reproduce this on production, but not on dev
- we do release the request's connection refs properly after receiving the response ( source: https://github.com/teamon/tesla/blob/master/lib/tesla/adapter/hackney.ex )
- I've struggled to make a reproduceable code sample to show to you, but unfortunately I couldn't so far. I can't share the production code., but I can tell that basically it does is making loads of POST requests with streamed body. 
- It seems like the issue doesn't appear when I do a request with normal body (non-streamed).

Any guesses what's wrong / workarounds? After reading comments in #420 and #391, seems like there might still be some case in which hackney hangs itself.

**Comment by silviucpp** [comment] 2017-12-13 15:24
We faced the same issues on production with GCM and only solution was to migrate to gun.

**Comment by benoitc** [comment] 2018-01-12 03:52
@silviucpp that's not helped to solve the issue in hackney apparently... 

@jtomaszewski  When do you get the timeout? Is this returned when you do the request or before that? In last case it should normally recreate a connection for you, is this on the latest release? 

There are different  possible reason to that timeout:

- the elasticsearch cluster close the connection without shuttding it down properly
- the cluster doesn't handle properly the keepalive, in such case it should have returned a close header but sometimes it doesn't, can you provide me a trace (by enabling it using hackney_trace) ? A way to circumvent that is to pass all the requests using the `{<<"Connection">>,<<"close">>}` header.

You can drop me a direct mail with the trace if you prefer.

Let me know.

**Comment by silviucpp** [comment] 2018-01-12 09:25
@benoitc I perfectly understand this. we opened ticket at some point in hackney but some peoples start telling that's a problem with the server and not with hackney. The fact that we migrated to another client and all problems gone now we have the confirmation that something behaves wrong in hackney.

**Comment by benoitc** [comment] 2018-01-12 09:40
Thanks for your answer!  on the other hand it can also be that gun is doing some magic reconnection behind. Anyway if you have still the info or the issue number that would be much appreciated.

**Comment by silviucpp** [comment] 2018-01-12 10:17
You can check the comments from https://github.com/benoitc/hackney/pull/453

**Comment by benoitc** [comment] 2018-01-23 09:33
@jtomaszewski you didn't answered to my comment... anyway please try the latest stable version 0.11.0 which fix the queue deletion in the pool. Let me know if it's fixes your issue or if more investigation are needed.

**Comment by jtomaszewski** [comment] 2018-01-24 12:28
Thank you for the fixes. 

Unfortunately we won't be able to reproduce it, at least not now, because we managed to fix it already with a workaround (we debounce connections sent to hackney on our own with [flow](https://github.com/elixir-lang/flow), as not to throttle it too much). I'll comment here again if I have a moment to rollback our changes and try to reproduce it again.

FYI: We've no more issues with hackney now. This case appeared very rarely, when we had thousands of connections sent to hackney at the same time. Thank you for your help!

**Comment by aaronrenner** [comment] 2018-03-14 17:45
Unfortunately, I'm continuing to get this issue on hackney 1.11.0. I'm using the Elixir [Honeybadger client (0.8.0)](https://github.com/honeybadger-io/honeybadger-elixir/tree/v0.8.0) and when too many errors are reported at the same time, the pool hangs. Here's the state of the pool:

```
iex(1)> pid = :hackney_pool.find_pool(Honeybadger.Client)
#PID<0.1550.0>
iex(2)> :sys.get_state(pid)
{:state, Honeybadger.Client, {:metrics_ng, :metrics_dummy}, 20, 150000,
 {:dict, 20, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[[#Reference<0.3303539597.571998211.241765> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.572522497.218728> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.573571078.11523> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.572522503.100366> |
      {'api.honeybadger.io', 443, :hackney_ssl}]], [],
    [[#Reference<0.3303539597.572522504.28966> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.573308935.261833> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.572522497.253425> |
      {'api.honeybadger.io', 443, :hackney_ssl}],
     [#Reference<0.3303539597.572784641.81062> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.572522498.114482> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.573046788.4759> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.573308930.182472> |
      {'api.honeybadger.io', 443, :hackney_ssl}],
     [#Reference<0.3303539597.573308934.184480> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.573308935.260196> |
      {'api.honeybadger.io', 443, :hackney_ssl}],
     [#Reference<0.3303539597.573571079.139285> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.572522502.8601> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.571998212.101950> |
      {'api.honeybadger.io', 443, :hackney_ssl}],
     [#Reference<0.3303539597.573571080.95577> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.573308936.149929> |
      {'api.honeybadger.io', 443, :hackney_ssl}],
     [#Reference<0.3303539597.573571079.25120> |
      {'api.honeybadger.io', 443, :hackney_ssl}]],
    [[#Reference<0.3303539597.572784643.74444> |
      {'api.honeybadger.io', 443, :hackney_ssl}]]}}},
 {:dict, 1, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[], [],
    [[{'api.honeybadger.io', 443, :hackney_ssl} |
      {[{{#PID<0.1549.0>, #Reference<0.3303539597.591134721.52478>},
         #Reference<0.3303539597.591134721.52476>}], []}]], [], [], [], [], [],
    [], [], [], [], [], [], [], []}}},
 {:dict, 0, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}},
 {:dict, 0, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []}}}, 1}
```
Please let me know if there's other tracing/logging I can provide. Thanks!

**Comment by aaronrenner** [comment] 2018-03-16 20:00
Looks like the behavior I pasted above is actually an issue with honeybadger: https://github.com/honeybadger-io/honeybadger-elixir/pull/133. Hackney is working as expected!

**Comment by jonzlin95** [comment] 2018-03-17 11:50
I (think) that I am still facing this issue on the latest version (1.11.0) of hackney (through use of the HTTPoison library.

I've set the pool to 500 connections, but still noticing that they're getting exhausted over time.
```no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :connect_timeout}}```

Going to try bumping the connection count, and will report back in.

**Comment by josevalim** [comment] 2018-04-02 18:59
@jonzlin95 @aaronrenner are you using Task.async/await?

@britto and @ulissesalmeida have recently found an issue where Hackney is no reclaiming timed out connections when the process that terminates the request terminates due to a link. Take for example this Erlang code:

    spawn_link(fn ->
      hackney:request("somewherethatwilltimeout")
    end),
    timer:sleep(1000),
    exit(timeout)

The parent process will terminate, causing the process that has done a request to also crash due to the link and then the connection is never reclaimed.

**Comment by jonzlin95** [comment] 2018-04-02 19:04
Not using Task.async/await, but I'm using the parallel_stream library.

**Comment by josevalim** [comment] 2018-04-02 19:44
@jonzlin95 that would likely introduce the same sort of problem, yeah.

**Comment by rozap** [comment] 2018-04-02 22:33
@jonzlin95 the thing i've noticed is that with @josevalim's example - that the exit needs to happen *while the request is waiting for a connection from the pool*. Otherwise it doesn't leak. 

```
defmodule HackneyDeadlocks do
  def run(url, n) do
    Enum.map(0..n, fn _ ->
      spawn(fn ->
        spawn_link(fn ->
          {:ok, 200, _headers, ref} = :hackney.get(url, [], <<>>, [
            connect_timeout: 1_000,
            recv_timeout: 1_000
          ])

          do_stream_body(ref, "")
        end)
        :timer.sleep(500)

        exit(:timeout)
      end)
    end)
  end
end
```

For example, running this many times over and over doesn't result in a leak
```
iex> HackneyDeadlocks.run("https://httparrot.herokuapp.com/delay/5", 50)
iex> :sys.get_state(:hackney_pool.find_pool(:default))
```
But running this just once, results in around ~300 leaked connections - which never complete and therefore block all subsequent requests
```elixir
iex> HackneyDeadlocks.run("https://httparrot.herokuapp.com/delay/5", 550)
iex> :sys.get_state(:hackney_pool.find_pool(:default))
```

**Comment by benoitc** [comment] 2018-04-03 08:06
@jtomaszewski thanks for the example,it helps! The process exit should be catched by the manager and then released in the pool. It looked a case is missed. I'm having a look on it.

**Comment by benoitc** [comment] 2018-04-03 09:06
I'va added the test in 505c06c5f4644963e25eacbd8543d94e1ac816ca and was able to reproduce it. At the end of the test I get the following stats (using the new `hackney:get_stats/1` function):

```
 [{name,default},{max,50},{in_use_count,49},{free_count,-1},{queue_count,431}]
```

So it seems that the queue is not freed. I'm looking at it.

**Comment by benoitc** [comment] 2018-04-03 10:19
@jtomaszewski @jonzlin95  #497 shoudl fix your issue. Can you test it? If it pass I will do a release today with it.  Let me know :)

**Closed** 2018-04-03 11:20 UTC
Labels: bug, need fedback

**Comment by benoitc** [comment] 2018-04-03 12:24
1.12 has been released with that fix. thanks @josevalim  & others for the reproducible way :)

**Comment by rozap** [comment] 2018-04-03 16:32
thanks @benoitc!
