### ISSUE TITLE
dependency is unable to support erlang 18.0

### ISSUE THREAD

**Issue by ramka001** [benoitc/hackney#264] opened 2015-11-25 16:16 UTC
Hi I'm currently trying to use hackney, but i'm getting a compile time error saying that one of the dependencies is not compatible with erlang 18.0.

**Comment by benoitc** [comment] 2015-11-25 16:21
i am running hackney on 18.1. Can you paste the error you have? Or at least tell me which dependency is not compatible?

**Comment by ramka001** [comment] 2015-11-27 11:25
the  {mimerl, "1.0.0"},  deps was failing

**Comment by benoitc** [comment] 2015-12-01 10:43
@ramka001 so you're using rebar2 right? I will test. With rebar3 I can't reproduce it.

**Comment by ramka001** [comment] 2015-12-01 10:55
Yes I'm using rebar 2

**Comment by benoitc** [comment] 2015-12-01 11:06
Just tried the latest master with rebar 2. So far I don't reproduce the issue, so not sure what is happening for you. Can you try to use rebar with the debug logs?

```
[hackney] rebar get-deps                                                                                                                                      ==> hackney (get-deps)
Pulling idna from {git,"https://github.com/benoitc/erlang-idna",{tag,"1.0.2"}}
Cloning into 'idna'...
Pulling mimerl from {git,"https://github.com/benoitc/mimerl",{tag,"1.0.1"}}
Cloning into 'mimerl'...
Pulling certifi from {git,"https://github.com/certifi/erlang-certifi",
                          {tag,"0.3.0"}}
Cloning into 'certifi'...
Pulling ssl_verify_hostname from {git,"https://github.com/deadtrickster/ssl_verify_hostname.erl",
                                      {tag,"1.0.5"}}
Cloning into 'ssl_verify_hostname'...
==> idna (get-deps)
WARN:  Missing plugins: [rebar3_hex]
==> mimerl (get-deps)
==> certifi (get-deps)
==> ssl_verify_hostname (get-deps)
[hackney] vim rebar.config                                                                                                                                     12:02:58  ☁  master ☀
[hackney] rebar compile                                                                                                                                        12:03:18  ☁  master ☀
==> idna (compile)
Compiled src/idna_unicode.erl
Compiled src/punycode.erl
Compiled src/idna.erl
Compiled src/idna_ucs.erl
Compiled src/idna_unicode_data.erl
WARN:  Missing plugins: [rebar3_hex]
==> mimerl (compile)
Compiled src/mimerl.erl
==> certifi (compile)
Compiled src/certifi.erl
Compiled src/certifi_weak.erl
Compiled src/certifi_cacerts.erl
==> ssl_verify_hostname (compile)
Compiled src/ssl_verify_hostname.erl
==> hackney (compile)
Compiled src/socket/hackney_tcp_transport.erl
Compiled src/socket/hackney_ssl_transport.erl
Compiled src/socket/hackney_pool_handler.erl
Compiled src/socket/hackney_socks5.erl
Compiled src/socket/hackney_http_connect.erl
Compiled src/metrics/hackney_folsom_metrics.erl
Compiled src/metrics/hackney_exometer_metrics.erl
Compiled src/metrics/hackney_dummy_metrics.erl
Compiled src/socket/hackney_pool.erl
Compiled src/socket/hackney_connect.erl
Compiled src/http/hackney_url.erl
Compiled src/http/hackney_response.erl
Compiled src/http/hackney_multipart.erl
Compiled src/http/hackney_request.erl
Compiled src/http/hackney_http.erl
Compiled src/http/hackney_cookie.erl
Compiled src/http/hackney_date.erl
Compiled src/http/hackney_headers.erl
Compiled src/hackney_util.erl
Compiled src/http/hackney_bstr.erl
Compiled src/hackney_sup.erl
Compiled src/hackney_trace.erl
Compiled src/hackney_app.erl
Compiled src/hackney_stream.erl
Compiled src/hackney_manager.erl
Compiled src/hackney.erl
[hackney]
```

**Comment by benoitc** [comment] 2015-12-19 20:57
no answer since, also not reproduced. closing the issue.

**Closed by benoitc** 2015-12-19 20:57 UTC
