### ISSUE TITLE
External API not specifying content-length

### ISSUE THREAD

**Issue by pcorey** [benoitc/hackney#471] opened 2018-02-06 01:15 UTC
Hello,

I'm using `hackney` via Elixir's `httpoison`.

I'm trying to query an external JSON API. Specifically, I'm trying to `GET` the following endpoint:

```
http://api.wordnik.com/v4/word.json/tomato/hyphenation?api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5
```

In the browser and with curl, it returns a JSON response:

```
[{"seq":0,"text":"to"},{"seq":1,"text":"ma","type":"stress"},{"seq":2,"text":"to"}]
```

Unfortunately, the response doesn't specify a `content-length`. It looks like version `1.11.0` of `hackney` [changed how unspecified `content-length` works (and now defaults to zero?)](https://github.com/benoitc/hackney/commit/5b51fb82547dd3a492aaac5d63f7aa1ada1e65cf). This means that the resulting `body` is an empty string, rather than the expected JSON.

It looks like previous versions of `hackney` (<= `1.10.0`) handled this unspecified `content-length` correctly and returned the JSON, as expected.

While I understand that not specifying a `content-length` isn't great, I'm not in any position to make changes to this external API. Is `hackney`'s current behavior intended? If so, is there a way to support the old behavior as well?

Thanks!

**Comment by PatNowak** [comment] 2018-02-06 11:59
I experienced the same thing today, it ruined my scrum review session :/

**Comment by benoitc** [comment] 2018-02-28 05:05
#481 should fix it. Can you test and let me know?

**Comment by benoitc** [comment] 2018-03-01 15:21
duplicate of #475. Please refer to it for more info.

**Closed by benoitc** 2018-03-01 15:21 UTC
Labels: to schedule
