### ISSUE TITLE
Clarification: what happens to a lost body ref?

### ISSUE THREAD

**Issue by eproxus** [benoitc/hackney#233] opened 2015-08-26 14:37 UTC
I couldn't find anything in the documentation about `hackney:body(BodyRef)` being mandatory or not. What happens if I don't call it for a response I'm not interested in?

**Comment by benoitc** [comment] 2015-08-27 13:53
Losing body_ref? In which case?

Anyway, a request is living until the process is alive. If you loose the request reference, data will be kept in the current process (in 1.3.x) and a metadata will stay in the hackney_manager ETS. If the process exit all metadata and buffers will be closed. The socket will also be closed.

Hope I answered to your question.

**Comment by eproxus** [comment] 2015-08-27 13:55
So not calling `hackney:body(BodyRef)` from a long running process is usually a bad idea? (Leading to some temporary memory leak)

**Comment by benoitc** [comment] 2015-08-27 14:00
If you don't call it the socket will never be released to the pool neither closed. It may also be the cause of a memory leak if many process are doing the same. Note that the buffer is relatively small since hackney is streaming all the request.

If you don't need the body, you can either fetch it when doing the request using the `with_body` option , or cal the function `hackney:skip_body(Ref)` if you need it. For now unfortunately skipping the body is synchronous.

If you server support it you can also do an `HEAD` request if the requested service supports it.

**Comment by eproxus** [comment] 2015-08-27 14:14
Make's sense. Thank you for the clarification.

**Comment by benoitc** [comment] 2015-09-05 22:15
@eproxus thanks for the feedback! Closing the issue now. Feel free to comment if you have more questions :)

**Closed by benoitc** 2015-09-05 22:15 UTC
Labels: Documentation
