### ISSUE TITLE
pool cannot be used along with http proxy

### ISSUE THREAD

**Issue by ananthakumaran** [benoitc/hackney#355] opened 2016-10-27 11:04 UTC
when pooling is used along with http proxy, hackney reuses the wrong connection and sends the request to different domain than intended.

Example

make request to s3
make request to mailgun

For the second request, instead of creating a new connection to mailgun, hackney reuses the connection to s3 and sends the payload there.

I have attached the trace of hackney_pool:checkout with and without proxy. The connections seem to be indexed by proxy's host/port rather than the real destination's host/port

```
without proxy
=============

(<0.70.0>) call hackney_pool:checkout("s3-ap-southeast-1.amazonaws.com",443,hackney_ssl_transport,{client,{1477,565345,811889},
        {metrics_ng,metrics_dummy},
        hackney_ssl_transport,"s3-ap-southeast-1.amazonaws.com",443,
        <<"s3-ap-southeast-1.amazonaws.com">>,
        [with_body,{recv_timeout,30000}],
        nil,nil,#Ref<0.0.1.1011>,true,hackney_pool,30000,false,5,false,5,nil,
        nil,nil,undefined,start,nil,normal,false,false,true,undefined,false,
        nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.70.0>) returned from hackney_pool:checkout/4 -> {error,no_socket,
                                                     {default,
                                                      #Ref<0.0.1.1011>,
                                                      {"s3-ap-southeast-1.amazonaws.com",
                                                       443,
                                                       hackney_ssl_transport},
                                                      <0.618.0>,
                                                      hackney_ssl_transport}}
(<0.70.0>) call hackney_pool:checkout("s3-ap-southeast-1.amazonaws.com",443,hackney_ssl_transport,{client,{1477,565347,234478},
        {metrics_ng,metrics_dummy},
        hackney_ssl_transport,"s3-ap-southeast-1.amazonaws.com",443,
        <<"s3-ap-southeast-1.amazonaws.com">>,
        [with_body,{recv_timeout,30000}],
        nil,nil,#Ref<0.0.2.4718>,true,hackney_pool,30000,false,5,false,5,nil,
        nil,nil,undefined,start,nil,normal,false,false,true,undefined,false,
        nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.70.0>) returned from hackney_pool:checkout/4 -> {ok,
                                                     {default,
                                                      #Ref<0.0.2.4718>,
                                                      {"s3-ap-southeast-1.amazonaws.com",
                                                       443,
                                                       hackney_ssl_transport},
                                                      <0.618.0>,
                                                      hackney_ssl_transport},
                                                     {sslsocket,
                                                      {gen_tcp,
                                                       #Port<0.28858>,
                                                       tls_connection,
                                                       undefined},
                                                      <0.619.0>}}

(<0.70.0>) call hackney_pool:checkout("api.mailgun.net",443,hackney_ssl_transport,{client,{1477,565347,509496},
        {metrics_ng,metrics_dummy},
        hackney_ssl_transport,"api.mailgun.net",443,<<"api.mailgun.net">>,
        [with_body],
        nil,nil,#Ref<0.0.2.4766>,true,hackney_pool,5000,false,5,false,5,nil,
        nil,nil,undefined,start,nil,normal,false,false,true,undefined,false,
        nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.70.0>) returned from hackney_pool:checkout/4 -> {error,no_socket,
                                                     {default,
                                                      #Ref<0.0.2.4766>,
                                                      {"api.mailgun.net",443,
                                                       hackney_ssl_transport},
                                                      <0.618.0>,
                                                      hackney_ssl_transport}}


(<0.70.0>) call hackney_pool:checkout("api.mailgun.net",443,hackney_ssl_transport,{client,{1477,565349,990939},
        {metrics_ng,metrics_dummy},
        hackney_ssl_transport,"api.mailgun.net",443,<<"api.mailgun.net">>,
        [with_body],
        nil,nil,#Ref<0.0.2.5009>,true,hackney_pool,5000,false,5,false,5,nil,
        nil,nil,undefined,start,nil,normal,false,false,true,undefined,false,
        nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.70.0>) returned from hackney_pool:checkout/4 -> {ok,
                                                     {default,
                                                      #Ref<0.0.2.5009>,
                                                      {"api.mailgun.net",443,
                                                       hackney_ssl_transport},
                                                      <0.618.0>,
                                                      hackney_ssl_transport},
                                                     {sslsocket,
                                                      {gen_tcp,
                                                       #Port<0.30326>,
                                                       tls_connection,
                                                       undefined},
                                                      <0.622.0>}}

with proxy
==========

(<0.70.0>) call hackney_pool:checkout("10.128.10.16",3128,hackney_http_connect,{client,{1477,565364,71935},
        {metrics_ng,metrics_dummy},
        hackney_http_connect,"10.128.10.16",3128,<<"10.128.10.16:3128">>,
        [with_body,
         {proxy,{"10.128.10.16",3128}},
         {connect_options,[{insecure,false},
                           {connect_host,"s3-ap-southeast-1.amazonaws.com"},
                           {connect_port,443},
                           {connect_transport,hackney_ssl_transport},
                           {connect_user,undefined},
                           {connect_pass,<<>>}]}],
        nil,nil,#Ref<0.0.1.1356>,true,hackney_pool,5000,false,5,false,5,nil,
        nil,nil,undefined,start,nil,normal,false,false,true,undefined,false,
        nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.70.0>) returned from hackney_pool:checkout/4 -> {error,no_socket,
                                                     {default,
                                                      #Ref<0.0.1.1356>,
                                                      {"10.128.10.16",3128,
                                                       hackney_http_connect},
                                                      <0.618.0>,
                                                      hackney_http_connect}}

(<0.70.0>) call hackney_pool:checkout("10.128.10.16",3128,hackney_http_connect,{client,{1477,565369,708158},
        {metrics_ng,metrics_dummy},
        hackney_http_connect,"10.128.10.16",3128,<<"10.128.10.16:3128">>,
        [with_body,
         {proxy,{"10.128.10.16",3128}},
         {connect_options,[{insecure,false},
                           {connect_host,"s3-ap-southeast-1.amazonaws.com"},
                           {connect_port,443},
                           {connect_transport,hackney_ssl_transport},
                           {connect_user,undefined},
                           {connect_pass,<<>>}]}],
        nil,nil,#Ref<0.0.1.1883>,true,hackney_pool,5000,false,5,false,5,nil,
        nil,nil,undefined,start,nil,normal,false,false,true,undefined,false,
        nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.70.0>) returned from hackney_pool:checkout/4 -> {ok,
                                                     {default,
                                                      #Ref<0.0.1.1883>,
                                                      {"10.128.10.16",3128,
                                                       hackney_http_connect},
                                                      <0.618.0>,
                                                      hackney_http_connect},
                                                     {hackney_ssl_transport,
                                                      {sslsocket,
                                                       {gen_tcp,
                                                        #Port<0.28532>,
                                                        tls_connection,
                                                        undefined},
                                                       <0.620.0>}}}

(<0.70.0>) call hackney_pool:checkout("10.128.10.16",3128,hackney_http_connect,{client,{1477,565369,979725},
        {metrics_ng,metrics_dummy},
        hackney_http_connect,"10.128.10.16",3128,<<"10.128.10.16:3128">>,
        [with_body,
         {proxy,{"10.128.10.16",3128}},
         {connect_options,[{insecure,false},
                           {connect_host,"api.mailgun.net"},
                           {connect_port,443},
                           {connect_transport,hackney_ssl_transport},
                           {connect_user,undefined},
                           {connect_pass,<<>>}]}],
        nil,nil,#Ref<0.0.1.1936>,true,hackney_pool,5000,false,5,false,5,nil,
        nil,nil,undefined,start,nil,normal,false,false,true,undefined,false,
        nil,waiting,nil,4096,<<>>,[],undefined,nil,nil,nil,nil,undefined,nil})
(<0.70.0>) returned from hackney_pool:checkout/4 -> {ok,
                                                     {default,
                                                      #Ref<0.0.1.1936>,
                                                      {"10.128.10.16",3128,
                                                       hackney_http_connect},
                                                      <0.618.0>,
                                                      hackney_http_connect},
                                                     {hackney_ssl_transport,
                                                      {sslsocket,
                                                       {gen_tcp,
                                                        #Port<0.28532>,
                                                        tls_connection,
                                                        undefined},
                                                       <0.620.0>}}}

```

**Comment by benoitc** [comment] 2016-10-28 11:50
confirmed. I will fix it over the week-end

**Comment by tslcjames** [comment] 2016-11-22 03:12
@benoitc I also saw `:closed` exception when I call `post` method,
but it's not always happened
is it related?

**Comment by rhruiz** [comment] 2017-01-04 19:29
👍 

Had to disable `use_default_pool` because of this.

**Comment by benoitc** [comment] 2017-01-04 20:35
a new version of hackney is landing sometimes this week that will fix that.

**Comment by Zert** [comment] 2017-02-16 13:08
Is this bug fixed yet?

**Comment by benoitc** [comment] 2017-07-28 09:44
no. the bug would be closed either way. Planned for coming month.

**Comment by chenxsan** [comment] 2017-10-04 09:54
Just add

```
config :hackney,
  use_default_pool: false
```
to `dev.exs` to disable `use_default_pool` until this is fixed :)

**Comment by thang911pk** [comment] 2019-05-15 21:41
Is this bug fixed yet?

**Comment by benoitc** [comment] 2020-05-25 00:37
this is now fixed in master. Sorry for the delay?

**Closed by benoitc** 2020-05-25 00:37 UTC
Labels: bug, pool, proxy
