### ISSUE TITLE
Passing non-binary values as headers

### ISSUE THREAD

**Issue by bernardd** [benoitc/hackney#405] opened 2017-05-02 09:44 UTC
Somewhere between v1.6.6 and 1.7 the implicitly accepted type (as determined by dialyzer) for `Headers` in `hackney:request/5` changed from a proplist with strings or binaries to one with binaries only. Is it intended that the `Headers` parameter should only ever be `[{binary(), binary()}]` or should `[{list(), list()}]` also be allowed? The spec for `request/5` only specifies `list()`, and the docs don't give any more clues.
I'm not bothered either way, I just want to know if I should patch hackney or the library I have that's calling it :)

**Comment by benoitc** [comment] 2017-05-03 08:29
@bernardd hrm sounds like a regression for an 1.x version. 
I expect in the future to only use binaries as headers since it makes things more efficient, but I guess the current release should be fixed. Thoughts?

**Comment by bernardd** [comment] 2017-05-04 12:10
I'd agree - assuming you're following a roughly semantic versioning approach where minor version changes shouldn't break APIs, I'd say it's definitely a regression that should be fixed. If the docs had been clear about being binary-only that would be one thing (even if the code had been more liberal in what it accepted) but given that evidently at least some other library authors were using other types I think it's reasonable to fix it for at least the 1.x series.

**Comment by benoitc** [comment] 2017-05-20 19:14
closing the issue. headers using a string as a key are accepted at the moment .

**Closed by benoitc** 2017-05-20 19:14 UTC
Labels: http, http11
